### ISSUE TITLE
update from ArteryTek/openocd

### ISSUE THREAD

**Issue by bkleiner** [amoxu/tool-openocd-at32#1]
Hi, Thanks for creating this repository.

The version currently in this repository seems to have some problems transferring the memory map to gdb and errors out with:
`Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'`

I built fresh binaries from ArteryTek/openocd, which resolves the issue, you can find the updated binaries [here](https://github.com/bkleiner/tool-openocd-at32).
To generate these binaries for the different platforms i have written a [github workflow](https://github.com/ArteryTek/openocd/compare/master...bkleiner:openocd:master) but i am missing the 32bit windows build.

I can submit a pull request.

**Comment by amoxu** [comment]
Thank you very much， Please submit a pull request.

Amo Xu
________________________________
From: Benedikt Kleiner ***@***.***>
Sent: Thursday, June 8, 2023 11:09:32 PM
To: amoxu/tool-openocd-at32 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amoxu/tool-openocd-at32] update from ArteryTek/openocd (Issue #1)


Hi, Thanks for creating this repository.

The version currently in this repository seems to have some problems transferring the memory map to gdb and errors out with:
Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'

I built fresh binaries from ArteryTek/openocd, which resolves the issue, you can find the updated binaries here<https://github.com/bkleiner/tool-openocd-at32>.
To generate these binaries for the different platforms i have written a github workflow<https://github.com/ArteryTek/openocd/compare/master...bkleiner:openocd:master> but i am missing the 32bit windows build.

I can submit a pull request.

**Comment by bkleiner** [comment]
Fixed in #2 and following
